---
title: "Lab 2 - Checkpoint 1"
author: "Arthur Costa"
date: "21 de maio de 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
```

# Há alguma relação entre a média da quantidade de votos de uma série e a nota média atribuída a ela?

```{r}
data = read_csv(here("data/series_from_imdb.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character())) %>% group_by(series_name, season) %>% summarise(media_notas = mean(user_rating), user_votes = mean(user_votes), n = n())
chart <- data %>% ggplot(aes(x = media_notas, y = user_votes)) +
            geom_point()
chart
plot_ly(data,
        x = data$media_notas,
        y = log(data$user_votes),
        size = data$n,
        text = data$series_name)
ggplotly(chart)

cor(data$media_notas, data$user_votes)
```

